### ISSUE TITLE
How to draw the Fig, 1&3 in the paper

### ISSUE THREAD

**Issue by falcon-xu** [micronDLA/MobileViTv3#2]
Hi, it's a wonderful work.
Could you please show the code of drawing the Fig, 1&3 in the paper or give some code demos? 
I don't know how to draw the analogous scatterplot as follows: 
![image](https://user-images.githubusercontent.com/58850615/195875837-da47831c-3a2d-4886-9f22-cee716c684c9.png)

I really appreciate it.

**Comment by codeAC29** [comment]
Unfortunately, we do not have any code for it. We used excel and tableau for our plots

**Comment by falcon-xu** [comment]
Get it. Thanks a lot.
