### ISSUE TITLE
why last layer self.conv_1x1_exp is Identity in code, but self.conv_1x1_exp is mapping to a higher dimension in paper?

### ISSUE THREAD

**Issue by xuesongnie** [micronDLA/MobileViTv3#4]
In code:
self.conv_1x1_exp = Identity()

In paper:
![屏幕截图 2022-11-13 125500](https://user-images.githubusercontent.com/113077897/201506481-2c0d879c-cca2-421c-8493-1fdffc5fbf73.jpg)

**Comment by shaktiwadekar9** [comment]
The table provides architecture details for MobileViTv3-XXS,XS, and S models [MobileViTv3-v1] and not for MobileViTv3-0.5,0.75 and 1.0 [MobileViTv3-v2]. The code part you are highlighting is present in the model definition for MobileViTv3-0.5,0.75 and 1.0. These models do not have conv-1x1 layer, therefore Identity() is used.

**Comment by xuesongnie** [comment]
> 

Thanks！

**Comment by xuesongnie** [comment]
> The table provides architecture details for MobileViTv3-XXS,XS, and S models [MobileViTv3-v1] and not for MobileViTv3-0.5,0.75 and 1.0 [MobileViTv3-v2]. The code part you are highlighting is present in the model definition for MobileViTv3-0.5,0.75 and 1.0. These models do not have conv-1x1 layer, therefore Identity() is used.

Thanks！
